# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/clion/103/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /snap/clion/103/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nikita/CLionProjects/json_deserializer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nikita/CLionProjects/json_deserializer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/snap/clion/103/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/snap/clion/103/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/snap/clion/103/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/clion/103/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/snap/clion/103/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/snap/clion/103/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/snap/clion/103/bin/cmake/linux/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/snap/clion/103/bin/cmake/linux/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nikita/CLionProjects/json_deserializer/CMakeFiles /home/nikita/CLionProjects/json_deserializer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nikita/CLionProjects/json_deserializer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named json_deserializer

# Build rule for target.
json_deserializer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 json_deserializer
.PHONY : json_deserializer

# fast build rule for target.
json_deserializer/fast:
	$(MAKE) -f CMakeFiles/json_deserializer.dir/build.make CMakeFiles/json_deserializer.dir/build
.PHONY : json_deserializer/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) -f json/CMakeFiles/ContinuousSubmit.dir/build.make json/CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) -f json/CMakeFiles/ContinuousMemCheck.dir/build.make json/CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) -f json/CMakeFiles/ContinuousConfigure.dir/build.make json/CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) -f json/CMakeFiles/ExperimentalSubmit.dir/build.make json/CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) -f json/CMakeFiles/ExperimentalMemCheck.dir/build.make json/CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) -f json/CMakeFiles/ExperimentalTest.dir/build.make json/CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) -f json/CMakeFiles/ContinuousTest.dir/build.make json/CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) -f json/CMakeFiles/ContinuousUpdate.dir/build.make json/CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) -f json/CMakeFiles/ExperimentalBuild.dir/build.make json/CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) -f json/CMakeFiles/NightlyMemoryCheck.dir/build.make json/CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) -f json/CMakeFiles/NightlyBuild.dir/build.make json/CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) -f json/CMakeFiles/ExperimentalUpdate.dir/build.make json/CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) -f json/CMakeFiles/ContinuousBuild.dir/build.make json/CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) -f json/CMakeFiles/Continuous.dir/build.make json/CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) -f json/CMakeFiles/Experimental.dir/build.make json/CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) -f json/CMakeFiles/ExperimentalConfigure.dir/build.make json/CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) -f json/CMakeFiles/NightlyStart.dir/build.make json/CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) -f json/CMakeFiles/NightlyTest.dir/build.make json/CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) -f json/CMakeFiles/NightlyUpdate.dir/build.make json/CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) -f json/CMakeFiles/ContinuousCoverage.dir/build.make json/CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) -f json/CMakeFiles/ExperimentalStart.dir/build.make json/CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) -f json/CMakeFiles/Nightly.dir/build.make json/CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) -f json/CMakeFiles/NightlyConfigure.dir/build.make json/CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) -f json/CMakeFiles/NightlyCoverage.dir/build.make json/CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) -f json/CMakeFiles/ExperimentalCoverage.dir/build.make json/CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) -f json/CMakeFiles/NightlyMemCheck.dir/build.make json/CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) -f json/CMakeFiles/ContinuousStart.dir/build.make json/CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) -f json/CMakeFiles/NightlySubmit.dir/build.make json/CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named test-wstring

# Build rule for target.
test-wstring: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-wstring
.PHONY : test-wstring

# fast build rule for target.
test-wstring/fast:
	$(MAKE) -f json/test/CMakeFiles/test-wstring.dir/build.make json/test/CMakeFiles/test-wstring.dir/build
.PHONY : test-wstring/fast

#=============================================================================
# Target rules for targets named test-unicode

# Build rule for target.
test-unicode: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-unicode
.PHONY : test-unicode

# fast build rule for target.
test-unicode/fast:
	$(MAKE) -f json/test/CMakeFiles/test-unicode.dir/build.make json/test/CMakeFiles/test-unicode.dir/build
.PHONY : test-unicode/fast

#=============================================================================
# Target rules for targets named test-udt

# Build rule for target.
test-udt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-udt
.PHONY : test-udt

# fast build rule for target.
test-udt/fast:
	$(MAKE) -f json/test/CMakeFiles/test-udt.dir/build.make json/test/CMakeFiles/test-udt.dir/build
.PHONY : test-udt/fast

#=============================================================================
# Target rules for targets named test-ubjson

# Build rule for target.
test-ubjson: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-ubjson
.PHONY : test-ubjson

# fast build rule for target.
test-ubjson/fast:
	$(MAKE) -f json/test/CMakeFiles/test-ubjson.dir/build.make json/test/CMakeFiles/test-ubjson.dir/build
.PHONY : test-ubjson/fast

#=============================================================================
# Target rules for targets named test-to_chars

# Build rule for target.
test-to_chars: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-to_chars
.PHONY : test-to_chars

# fast build rule for target.
test-to_chars/fast:
	$(MAKE) -f json/test/CMakeFiles/test-to_chars.dir/build.make json/test/CMakeFiles/test-to_chars.dir/build
.PHONY : test-to_chars/fast

#=============================================================================
# Target rules for targets named test-serialization

# Build rule for target.
test-serialization: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-serialization
.PHONY : test-serialization

# fast build rule for target.
test-serialization/fast:
	$(MAKE) -f json/test/CMakeFiles/test-serialization.dir/build.make json/test/CMakeFiles/test-serialization.dir/build
.PHONY : test-serialization/fast

#=============================================================================
# Target rules for targets named test-convenience

# Build rule for target.
test-convenience: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-convenience
.PHONY : test-convenience

# fast build rule for target.
test-convenience/fast:
	$(MAKE) -f json/test/CMakeFiles/test-convenience.dir/build.make json/test/CMakeFiles/test-convenience.dir/build
.PHONY : test-convenience/fast

#=============================================================================
# Target rules for targets named test-class_iterator

# Build rule for target.
test-class_iterator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-class_iterator
.PHONY : test-class_iterator

# fast build rule for target.
test-class_iterator/fast:
	$(MAKE) -f json/test/CMakeFiles/test-class_iterator.dir/build.make json/test/CMakeFiles/test-class_iterator.dir/build
.PHONY : test-class_iterator/fast

#=============================================================================
# Target rules for targets named test-class_parser

# Build rule for target.
test-class_parser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-class_parser
.PHONY : test-class_parser

# fast build rule for target.
test-class_parser/fast:
	$(MAKE) -f json/test/CMakeFiles/test-class_parser.dir/build.make json/test/CMakeFiles/test-class_parser.dir/build
.PHONY : test-class_parser/fast

#=============================================================================
# Target rules for targets named test-comparison

# Build rule for target.
test-comparison: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-comparison
.PHONY : test-comparison

# fast build rule for target.
test-comparison/fast:
	$(MAKE) -f json/test/CMakeFiles/test-comparison.dir/build.make json/test/CMakeFiles/test-comparison.dir/build
.PHONY : test-comparison/fast

#=============================================================================
# Target rules for targets named test-regression

# Build rule for target.
test-regression: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-regression
.PHONY : test-regression

# fast build rule for target.
test-regression/fast:
	$(MAKE) -f json/test/CMakeFiles/test-regression.dir/build.make json/test/CMakeFiles/test-regression.dir/build
.PHONY : test-regression/fast

#=============================================================================
# Target rules for targets named test-class_const_iterator

# Build rule for target.
test-class_const_iterator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-class_const_iterator
.PHONY : test-class_const_iterator

# fast build rule for target.
test-class_const_iterator/fast:
	$(MAKE) -f json/test/CMakeFiles/test-class_const_iterator.dir/build.make json/test/CMakeFiles/test-class_const_iterator.dir/build
.PHONY : test-class_const_iterator/fast

#=============================================================================
# Target rules for targets named test-json_patch

# Build rule for target.
test-json_patch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-json_patch
.PHONY : test-json_patch

# fast build rule for target.
test-json_patch/fast:
	$(MAKE) -f json/test/CMakeFiles/test-json_patch.dir/build.make json/test/CMakeFiles/test-json_patch.dir/build
.PHONY : test-json_patch/fast

#=============================================================================
# Target rules for targets named test-noexcept

# Build rule for target.
test-noexcept: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-noexcept
.PHONY : test-noexcept

# fast build rule for target.
test-noexcept/fast:
	$(MAKE) -f json/test/CMakeFiles/test-noexcept.dir/build.make json/test/CMakeFiles/test-noexcept.dir/build
.PHONY : test-noexcept/fast

#=============================================================================
# Target rules for targets named test-pointer_access

# Build rule for target.
test-pointer_access: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-pointer_access
.PHONY : test-pointer_access

# fast build rule for target.
test-pointer_access/fast:
	$(MAKE) -f json/test/CMakeFiles/test-pointer_access.dir/build.make json/test/CMakeFiles/test-pointer_access.dir/build
.PHONY : test-pointer_access/fast

#=============================================================================
# Target rules for targets named test-class_lexer

# Build rule for target.
test-class_lexer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-class_lexer
.PHONY : test-class_lexer

# fast build rule for target.
test-class_lexer/fast:
	$(MAKE) -f json/test/CMakeFiles/test-class_lexer.dir/build.make json/test/CMakeFiles/test-class_lexer.dir/build
.PHONY : test-class_lexer/fast

#=============================================================================
# Target rules for targets named test-bson

# Build rule for target.
test-bson: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-bson
.PHONY : test-bson

# fast build rule for target.
test-bson/fast:
	$(MAKE) -f json/test/CMakeFiles/test-bson.dir/build.make json/test/CMakeFiles/test-bson.dir/build
.PHONY : test-bson/fast

#=============================================================================
# Target rules for targets named test-cbor

# Build rule for target.
test-cbor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-cbor
.PHONY : test-cbor

# fast build rule for target.
test-cbor/fast:
	$(MAKE) -f json/test/CMakeFiles/test-cbor.dir/build.make json/test/CMakeFiles/test-cbor.dir/build
.PHONY : test-cbor/fast

#=============================================================================
# Target rules for targets named test-algorithms

# Build rule for target.
test-algorithms: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-algorithms
.PHONY : test-algorithms

# fast build rule for target.
test-algorithms/fast:
	$(MAKE) -f json/test/CMakeFiles/test-algorithms.dir/build.make json/test/CMakeFiles/test-algorithms.dir/build
.PHONY : test-algorithms/fast

#=============================================================================
# Target rules for targets named test-element_access2

# Build rule for target.
test-element_access2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-element_access2
.PHONY : test-element_access2

# fast build rule for target.
test-element_access2/fast:
	$(MAKE) -f json/test/CMakeFiles/test-element_access2.dir/build.make json/test/CMakeFiles/test-element_access2.dir/build
.PHONY : test-element_access2/fast

#=============================================================================
# Target rules for targets named test-allocator

# Build rule for target.
test-allocator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-allocator
.PHONY : test-allocator

# fast build rule for target.
test-allocator/fast:
	$(MAKE) -f json/test/CMakeFiles/test-allocator.dir/build.make json/test/CMakeFiles/test-allocator.dir/build
.PHONY : test-allocator/fast

#=============================================================================
# Target rules for targets named test-items

# Build rule for target.
test-items: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-items
.PHONY : test-items

# fast build rule for target.
test-items/fast:
	$(MAKE) -f json/test/CMakeFiles/test-items.dir/build.make json/test/CMakeFiles/test-items.dir/build
.PHONY : test-items/fast

#=============================================================================
# Target rules for targets named test-constructor2

# Build rule for target.
test-constructor2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-constructor2
.PHONY : test-constructor2

# fast build rule for target.
test-constructor2/fast:
	$(MAKE) -f json/test/CMakeFiles/test-constructor2.dir/build.make json/test/CMakeFiles/test-constructor2.dir/build
.PHONY : test-constructor2/fast

#=============================================================================
# Target rules for targets named test-alt-string

# Build rule for target.
test-alt-string: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-alt-string
.PHONY : test-alt-string

# fast build rule for target.
test-alt-string/fast:
	$(MAKE) -f json/test/CMakeFiles/test-alt-string.dir/build.make json/test/CMakeFiles/test-alt-string.dir/build
.PHONY : test-alt-string/fast

#=============================================================================
# Target rules for targets named test-iterators2

# Build rule for target.
test-iterators2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-iterators2
.PHONY : test-iterators2

# fast build rule for target.
test-iterators2/fast:
	$(MAKE) -f json/test/CMakeFiles/test-iterators2.dir/build.make json/test/CMakeFiles/test-iterators2.dir/build
.PHONY : test-iterators2/fast

#=============================================================================
# Target rules for targets named test-capacity

# Build rule for target.
test-capacity: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-capacity
.PHONY : test-capacity

# fast build rule for target.
test-capacity/fast:
	$(MAKE) -f json/test/CMakeFiles/test-capacity.dir/build.make json/test/CMakeFiles/test-capacity.dir/build
.PHONY : test-capacity/fast

#=============================================================================
# Target rules for targets named test-conversions

# Build rule for target.
test-conversions: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-conversions
.PHONY : test-conversions

# fast build rule for target.
test-conversions/fast:
	$(MAKE) -f json/test/CMakeFiles/test-conversions.dir/build.make json/test/CMakeFiles/test-conversions.dir/build
.PHONY : test-conversions/fast

#=============================================================================
# Target rules for targets named test-constructor1

# Build rule for target.
test-constructor1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-constructor1
.PHONY : test-constructor1

# fast build rule for target.
test-constructor1/fast:
	$(MAKE) -f json/test/CMakeFiles/test-constructor1.dir/build.make json/test/CMakeFiles/test-constructor1.dir/build
.PHONY : test-constructor1/fast

#=============================================================================
# Target rules for targets named test-deserialization

# Build rule for target.
test-deserialization: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-deserialization
.PHONY : test-deserialization

# fast build rule for target.
test-deserialization/fast:
	$(MAKE) -f json/test/CMakeFiles/test-deserialization.dir/build.make json/test/CMakeFiles/test-deserialization.dir/build
.PHONY : test-deserialization/fast

#=============================================================================
# Target rules for targets named test-reference_access

# Build rule for target.
test-reference_access: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-reference_access
.PHONY : test-reference_access

# fast build rule for target.
test-reference_access/fast:
	$(MAKE) -f json/test/CMakeFiles/test-reference_access.dir/build.make json/test/CMakeFiles/test-reference_access.dir/build
.PHONY : test-reference_access/fast

#=============================================================================
# Target rules for targets named test-element_access1

# Build rule for target.
test-element_access1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-element_access1
.PHONY : test-element_access1

# fast build rule for target.
test-element_access1/fast:
	$(MAKE) -f json/test/CMakeFiles/test-element_access1.dir/build.make json/test/CMakeFiles/test-element_access1.dir/build
.PHONY : test-element_access1/fast

#=============================================================================
# Target rules for targets named test-meta

# Build rule for target.
test-meta: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-meta
.PHONY : test-meta

# fast build rule for target.
test-meta/fast:
	$(MAKE) -f json/test/CMakeFiles/test-meta.dir/build.make json/test/CMakeFiles/test-meta.dir/build
.PHONY : test-meta/fast

#=============================================================================
# Target rules for targets named test-inspection

# Build rule for target.
test-inspection: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-inspection
.PHONY : test-inspection

# fast build rule for target.
test-inspection/fast:
	$(MAKE) -f json/test/CMakeFiles/test-inspection.dir/build.make json/test/CMakeFiles/test-inspection.dir/build
.PHONY : test-inspection/fast

#=============================================================================
# Target rules for targets named doctest_main

# Build rule for target.
doctest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doctest_main
.PHONY : doctest_main

# fast build rule for target.
doctest_main/fast:
	$(MAKE) -f json/test/CMakeFiles/doctest_main.dir/build.make json/test/CMakeFiles/doctest_main.dir/build
.PHONY : doctest_main/fast

#=============================================================================
# Target rules for targets named test-readme

# Build rule for target.
test-readme: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-readme
.PHONY : test-readme

# fast build rule for target.
test-readme/fast:
	$(MAKE) -f json/test/CMakeFiles/test-readme.dir/build.make json/test/CMakeFiles/test-readme.dir/build
.PHONY : test-readme/fast

#=============================================================================
# Target rules for targets named test-iterators1

# Build rule for target.
test-iterators1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-iterators1
.PHONY : test-iterators1

# fast build rule for target.
test-iterators1/fast:
	$(MAKE) -f json/test/CMakeFiles/test-iterators1.dir/build.make json/test/CMakeFiles/test-iterators1.dir/build
.PHONY : test-iterators1/fast

#=============================================================================
# Target rules for targets named test-json_pointer

# Build rule for target.
test-json_pointer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-json_pointer
.PHONY : test-json_pointer

# fast build rule for target.
test-json_pointer/fast:
	$(MAKE) -f json/test/CMakeFiles/test-json_pointer.dir/build.make json/test/CMakeFiles/test-json_pointer.dir/build
.PHONY : test-json_pointer/fast

#=============================================================================
# Target rules for targets named test-modifiers

# Build rule for target.
test-modifiers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-modifiers
.PHONY : test-modifiers

# fast build rule for target.
test-modifiers/fast:
	$(MAKE) -f json/test/CMakeFiles/test-modifiers.dir/build.make json/test/CMakeFiles/test-modifiers.dir/build
.PHONY : test-modifiers/fast

#=============================================================================
# Target rules for targets named test-testsuites

# Build rule for target.
test-testsuites: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-testsuites
.PHONY : test-testsuites

# fast build rule for target.
test-testsuites/fast:
	$(MAKE) -f json/test/CMakeFiles/test-testsuites.dir/build.make json/test/CMakeFiles/test-testsuites.dir/build
.PHONY : test-testsuites/fast

#=============================================================================
# Target rules for targets named test-concepts

# Build rule for target.
test-concepts: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-concepts
.PHONY : test-concepts

# fast build rule for target.
test-concepts/fast:
	$(MAKE) -f json/test/CMakeFiles/test-concepts.dir/build.make json/test/CMakeFiles/test-concepts.dir/build
.PHONY : test-concepts/fast

#=============================================================================
# Target rules for targets named test-large_json

# Build rule for target.
test-large_json: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-large_json
.PHONY : test-large_json

# fast build rule for target.
test-large_json/fast:
	$(MAKE) -f json/test/CMakeFiles/test-large_json.dir/build.make json/test/CMakeFiles/test-large_json.dir/build
.PHONY : test-large_json/fast

#=============================================================================
# Target rules for targets named test-merge_patch

# Build rule for target.
test-merge_patch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-merge_patch
.PHONY : test-merge_patch

# fast build rule for target.
test-merge_patch/fast:
	$(MAKE) -f json/test/CMakeFiles/test-merge_patch.dir/build.make json/test/CMakeFiles/test-merge_patch.dir/build
.PHONY : test-merge_patch/fast

#=============================================================================
# Target rules for targets named test-msgpack

# Build rule for target.
test-msgpack: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-msgpack
.PHONY : test-msgpack

# fast build rule for target.
test-msgpack/fast:
	$(MAKE) -f json/test/CMakeFiles/test-msgpack.dir/build.make json/test/CMakeFiles/test-msgpack.dir/build
.PHONY : test-msgpack/fast

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/json_deserializer.dir/build.make CMakeFiles/json_deserializer.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/json_deserializer.dir/build.make CMakeFiles/json_deserializer.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/json_deserializer.dir/build.make CMakeFiles/json_deserializer.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/request_loader.o: src/request_loader.cpp.o

.PHONY : src/request_loader.o

# target to build an object file
src/request_loader.cpp.o:
	$(MAKE) -f CMakeFiles/json_deserializer.dir/build.make CMakeFiles/json_deserializer.dir/src/request_loader.cpp.o
.PHONY : src/request_loader.cpp.o

src/request_loader.i: src/request_loader.cpp.i

.PHONY : src/request_loader.i

# target to preprocess a source file
src/request_loader.cpp.i:
	$(MAKE) -f CMakeFiles/json_deserializer.dir/build.make CMakeFiles/json_deserializer.dir/src/request_loader.cpp.i
.PHONY : src/request_loader.cpp.i

src/request_loader.s: src/request_loader.cpp.s

.PHONY : src/request_loader.s

# target to generate assembly for a file
src/request_loader.cpp.s:
	$(MAKE) -f CMakeFiles/json_deserializer.dir/build.make CMakeFiles/json_deserializer.dir/src/request_loader.cpp.s
.PHONY : src/request_loader.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... json_deserializer"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install/local"
	@echo "... install"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousConfigure"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalTest"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... ExperimentalBuild"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyBuild"
	@echo "... ExperimentalUpdate"
	@echo "... ContinuousBuild"
	@echo "... Continuous"
	@echo "... Experimental"
	@echo "... ExperimentalConfigure"
	@echo "... NightlyStart"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... ContinuousCoverage"
	@echo "... ExperimentalStart"
	@echo "... Nightly"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... ExperimentalCoverage"
	@echo "... NightlyMemCheck"
	@echo "... ContinuousStart"
	@echo "... NightlySubmit"
	@echo "... test-wstring"
	@echo "... test-unicode"
	@echo "... test-udt"
	@echo "... test-ubjson"
	@echo "... test-to_chars"
	@echo "... test-serialization"
	@echo "... test-convenience"
	@echo "... test-class_iterator"
	@echo "... test-class_parser"
	@echo "... test-comparison"
	@echo "... test-regression"
	@echo "... test-class_const_iterator"
	@echo "... test-json_patch"
	@echo "... test-noexcept"
	@echo "... test-pointer_access"
	@echo "... test-class_lexer"
	@echo "... test-bson"
	@echo "... test-cbor"
	@echo "... test-algorithms"
	@echo "... test-element_access2"
	@echo "... test-allocator"
	@echo "... test-items"
	@echo "... test-constructor2"
	@echo "... test-alt-string"
	@echo "... test-iterators2"
	@echo "... test-capacity"
	@echo "... test-conversions"
	@echo "... test-constructor1"
	@echo "... test-deserialization"
	@echo "... test-reference_access"
	@echo "... test-element_access1"
	@echo "... test-meta"
	@echo "... test-inspection"
	@echo "... doctest_main"
	@echo "... test-readme"
	@echo "... test-iterators1"
	@echo "... test-json_pointer"
	@echo "... test-modifiers"
	@echo "... test-testsuites"
	@echo "... test-concepts"
	@echo "... test-large_json"
	@echo "... test-merge_patch"
	@echo "... test-msgpack"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/request_loader.o"
	@echo "... src/request_loader.i"
	@echo "... src/request_loader.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

